### ISSUE TITLE
Provide final testing for the project.

### ISSUE THREAD

**Issue by pakozh** [artemsmirnov/sesh#19]

**Comment by Sanchez486** [comment]
В каком виде необходимо его предоставить?

**Comment by pakozh** [comment]
Test case 1.
Description:
Execute "sesh -h" command as root;

Expected result:
"Some help text..." message is appear.

Result: FAIL/PASS

Test case 2....

**Comment by Sanchez486** [comment]
Я в том смысле, что это надо в виде какого то файла записать, типа "testin_Iteration2.txt"?
Или прямо сюда закинуть в комменты?
Или как вообще?)

**Comment by pakozh** [comment]
Удобнее всего, наверное, отдельную папку в корне репозитория сделать для тест-планов, отчетов по тестированию, автоматизированных скриптов для тестирования и чего там еще вам понадобится... Например: "/testing". Как файлы называть, смотрите сами, главное, чтобы название говорило, что это за файл. Например: "It2-test-report.txt".
Да, и желательно, чтобы это был обычный аски-текст. Фиг с ним с красивым форматированием, главное чтобы было удобно читать откуда угодно :)

**Comment by artyomxyz** [comment]
https://github.com/artemsmirnov/sesh/commit/2cf8faf4d3fcac818af3f8498d3e73695b6b7b55
