### ISSUE TITLE
очень плохая программа

### ISSUE THREAD

**Issue by WideWord** [artemsmirnov/sesh#4]
скачал програму, вопервых нет установщика все программисты делают установщикба у вас какой то не понятный файл открываеться очень медлено, нужно работать над оптимиъацией и вылаживатьь програму в установщике на пример inno setyp в нем может разобратся даже веб мастер вобщем программу мне запустить так и не у далось так-что ставлю этой программе 1 звезду, вылаживай в виндос сторе поставлю там, спасиббо за внемание

**Comment by artemsmirnov** [comment]
пососи хуй

**Comment by pakozh** [comment]
Это камень в мой огород?)

**Comment by WideWord** [comment]
Нее, просто ироничный коммент в стиле школьника-виндузятника)

**Comment by pakozh** [comment]
Да, не, все норм) просто похоже получилось на то что я сегодня утром говорил)
