### ISSUE TITLE
Shell crashes when trying to execute empty command

### ISSUE THREAD

**Issue by WideWord** [artemsmirnov/sesh#60]
I press enter without command, and then
![screen shot 2015-07-16 at 16 07 07](https://cloud.githubusercontent.com/assets/977448/8723430/309530ee-2bd6-11e5-8f5e-daf65d75f1b4.png)

**Comment by artyomxyz** [comment]
ммм, макбук, наша программа расчитана на redhat,ты проверял, воспроизводится ли ошибка на нём?

**Comment by WideWord** [comment]
Нет, к сожалению не хватило денег на оригинальный redhat

**Comment by artyomxyz** [comment]
Бедный любитель техники apple

**Comment by leshkajou** [comment]
petuhi C:
